#pragma once

#define MATRIX_ROWS 10
#define MATRIX_COLS 8 

#define SPLIT_WATCHDOG_ENABLE
#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define SPLIT_USB_DETECT
#define SPLIT_USB_TIMEOUT 2000
#define SERIAL_USART_SPEED 2000000
#define SPLIT_TRANSPORT_SYNC_INTERVAL 0
#define EE_HANDS
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP12
#define SERIAL_USART_RX_PIN GP13

#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 3
#define MOUSEKEY_TIME_TO_MAX 7
#define BOOTMAGIC_ROW_LEFT 0
#define BOOTMAGIC_COLUMN_LEFT 0
#define BOOTMAGIC_ROW_RIGHT 5
#define BOOTMAGIC_COLUMN_RIGHT 7

#define WS2812_DI_PIN GP23
#define RGB_DRIVER_VND WS2812
#define RGBLIGHT_LED_COUNT 1  
#define RGBLIGHT_LIMIT_VAL 50
#define RGBLIGHT_LAYERS
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_STATIC_LIGHT